approp_types <- tibble::tribble(
  ~Category                               , `COBI Org Alias` , ~Definition                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ,
  "State Budget"                          , "Not native"     , "These appropriations are what people typically mean when they talk about “the budget”. They sum Operating and Capital Budgets plus Expendable Funds and Accounts, as defined below."                                                                                                                                                                                                                                                                                                                                                                           ,
  "State Fund Expense"                    ,                  ,
  "Operating and Capital Budgets"         , "GEN"            , "These are appropriations that grant to agencies, divisions, and programs of state government authority to expend public money. With a few exceptions, spending is “capped” at the amount appropriated. This section includes one “business-like” activity - DABC - because its profit impacts General Fund revenue."                                                                                                                                                                                                                                       ,
  "Expendable Funds and Accounts"         , "ERF"            , "These items are, for the most part, “expendable special revenue funds” - funds and accounts that have a dedicated revenue source and can be spent without legislative action. The exceptions are enterprise funds and general fund restricted accounts that act like expendable special revenue funds. In some cases, these appropriations items also authorize the state Division of Finance to move resources from one fund or account into another fund or account where the recipient fund or account can be spent without additional legislative action." ,
  "Business-like Activites"               , "PRP"            , "Items of appropriation in this section authorize state entities to provide services to one another or the public in exchange for a rate of fee. Internal service fund budgets contained in this section are informational. These ISFs rather are controlled by employment caps, capital acquisition limits, and rate setting."                                                                                                                                                                                                                                     ,
  "Restricted Fund and Account Transfers" , "RAT"            , "These appropriations authorize the Division of Finance to move money from one restricted fund or account to another. Alone they do not increase spending. Money must be re-appropriated in another category."                                                                                                                                                                                                                                                                                                                                                      ,
  "Transfers to Unrestricted Funds"       , "FRT"            , "These appropriations authorize the Division of Finance to move money from a restricted fund or account to the unrestricted General or Education fund. Alone they do not increase spending. Money must be re-appropriated in another category."                                                                                                                                                                                                                                                                                                                     ,
  "Fiduciary Funds"                       , "FID"            , "These items of appropriation indicate that the Legislature has reviewed funds where the State has responsibility for other people's and organizations' money."                                                                                                                                                                                                                                                                                                                                                                                                     ,
  "Capital Project Funds"                 , "CPF"            , "These items show funds for roads, buildings, and other infrastructure that might include cash as well as borrowed money. They allow users to see the full impact of state investment in infrastructure, not only the cash-funded portion."                                                                                                                                                                                                                                                                                                                         ,
  "Higher Education Budget Reporting"     , "HED"            , "Beginning in FY 2025, the Legislature viewed state support for higher education in context using this roll-up. It adds state support to other higher education resources like federal funds, grants and aid, tuition and fees, and philanthropy. It allows policymakers to see how taxpayer dollars compare to these other sources at various institutions and what those taxpayer funds buy at universities and colleges."                                                                                                                                        ,
)

usethis::use_data(approp_types, overwrite = TRUE)
