utils::globalVariables(c(
  "%<>%",
  "FY",
  "CatType",
  "Agency",
  "Line_Item",
  "Appr_Unit",
  "Category",
  "years",
  "Agency_Name",
  "Line_Item_Desc",
  "Appr_Unit_Desc",
  "Last_Utilization_FY",
  "Line_Item_Cat",
  "Agency_Desc",
  "sessionFY"
))
